version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  kafka:
    image: bitnami/kafka:3.2.3
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka-data:/bitnami/kafka/data
    ports:
      - '9092:9092'

volumes:
  kafka-data:
    driver: local